"""empty message

Revision ID: 1f031b7735c5
Revises: 496d97235057
Create Date: 2015-07-15 22:33:40.747365

"""

# revision identifiers, used by Alembic.
revision = '1f031b7735c5'
down_revision = '496d97235057'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
