"""empty message

Revision ID: 3acd05a0152c
Revises: 5a62b7940cae
Create Date: 2015-07-10 14:54:28.339346

"""

# revision identifiers, used by Alembic.
revision = '3acd05a0152c'
down_revision = '5a62b7940cae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_groups')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('audio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audio'], [u'audio.id'], name=u'audio_groups_audio_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'audio_groups_pkey')
    )
    ### end Alembic commands ###
