"""empty message

Revision ID: 496d97235057
Revises: ea80674a1e2
Create Date: 2015-07-15 22:29:11.424610

"""

# revision identifiers, used by Alembic.
revision = '496d97235057'
down_revision = 'ea80674a1e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_tags', 'audio', new_column_name="audio_id")
    # op.drop_constraint(u'audio_tags_audio_fkey', 'audio_tags', type_='foreignkey')
    # op.create_foreign_key(None, 'audio_tags', 'audio', ['audio_id'], ['id'])
    # op.drop_column('audio_tags', 'audio')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_tags', 'audio_id', new_column_name="audio")
    ### end Alembic commands ###
