"""empty message

Revision ID: c4019e037a7
Revises: 5eed70a8121
Create Date: 2015-06-22 09:16:58.708591

"""

# revision identifiers, used by Alembic.
revision = 'c4019e037a7'
down_revision = '5eed70a8121'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('audio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio'], ['audio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('audio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio'], ['audio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_tags')
    op.drop_table('audio_groups')
    op.drop_table('audio')
    ### end Alembic commands ###
