"""empty message

Revision ID: ea80674a1e2
Revises: 3acd05a0152c
Create Date: 2015-07-13 16:02:46.336618

"""

# revision identifiers, used by Alembic.
revision = 'ea80674a1e2'
down_revision = '3acd05a0152c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
